// pokepractica/pokedex/pokedex-angular/src/app/app.ts
import { RouterOutlet } from '@angular/router';
import { Component, inject, OnInit, signal,computed } from '@angular/core';
import { PokemonService } from './services/pokemon.service';
import { TarjetaPokemonComponent } from './components/tarjeta-pokemon/tarjeta-pokemon.component';
import { FotoPrincipalComponent } from './components/foto-principal/foto-principal.component';
import { DetallePanelComponent } from './components/detalle-panel/detalle-panel.component';
import { FormsModule } from '@angular/forms';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [TarjetaPokemonComponent, FotoPrincipalComponent, DetallePanelComponent,FormsModule],
  templateUrl: './app.html',
  styleUrl: './app.css'
})
export class App implements OnInit {
  private pokemonService = inject(PokemonService);

  listaPokemons = signal<any[]>([]);
  pokemonSeleccionadoDetalles = signal<any>(null);

  textoBusqueda = signal<string>('');
  listaFiltrada = computed(() => {
    const texto = this.textoBusqueda().toLowerCase().trim();
    if (!texto) return this.listaPokemons();
    return this.listaPokemons().filter(p => p.name.toLowerCase().includes(texto));
  });

  private offset = 0;
  private readonly LIMITE = 11;
  private readonly TOPE_MAXIMO = 101;
  cargando = signal<boolean>(false);

  ngOnInit() {
    this.cargarMas();
  }
  cargarMas() {
    if (this.offset >= this.TOPE_MAXIMO || this.cargando()) return;

    this.cargando.set(true);

    this.pokemonService.obtenerLista(this.LIMITE, this.offset).subscribe(respuesta => {
      
      this.listaPokemons.update(actual => [...actual, ...respuesta.results]);

      if (this.offset === 0) {
        this.seleccionarPokemon(respuesta.results[0].name);
      }

      this.offset += this.LIMITE;
      this.cargando.set(false);
    });
  }

  onScroll(event: Event) {
    const el = event.target as HTMLElement;

    const llegueAlFondo = el.scrollTop + el.clientHeight >= el.scrollHeight - 50;

    if (llegueAlFondo) {
      this.cargarMas();
    }
  }

  seleccionarPokemon(nombre: string) {
    this.pokemonService.obtenerDetalles(nombre).subscribe(detalles => {
      this.pokemonSeleccionadoDetalles.set(detalles);
    });
  }
}

// pokepractica/pokedex/pokedex-react/src/App.jsx
import { useState, useEffect, useRef } from 'react';
import { obtenerListaPokemon, obtenerDetallesPokemon } from './services/pokemonService';
import TarjetaPokemon from './components/TarjetaPokemon';
import FotoPrincipal from './components/FotoPrincipal';
import DetallePanel from './components/DetallePanel';
import './App.css';

const LIMITE = 20;
const TOPE_MAXIMO = 101;

export default function App() {
  const [listaPokemons, setListaPokemons] = useState([]);
  const [detallesSeleccionado, setDetallesSeleccionado] = useState(null);
  const [textoBusqueda, setTextoBusqueda] = useState('');
  const [cargando, setCargando] = useState(false);
  const offsetRef = useRef(0);

  useEffect(() => {
    cargarMas();
  }, []);

  const cargarMas = () => {
    if (offsetRef.current >= TOPE_MAXIMO || cargando) return;
    setCargando(true);
    obtenerListaPokemon(LIMITE, offsetRef.current).then(datos => {
      setListaPokemons(actual => {
        if (offsetRef.current === 0) seleccionarPokemon(datos.results[0].name);
        return [...actual, ...datos.results];
      });
      offsetRef.current += LIMITE;
      setCargando(false);
    });
  };

  const seleccionarPokemon = (nombre) => {
    obtenerDetallesPokemon(nombre).then(detalles => {
      setDetallesSeleccionado(detalles);
    });
  };

  const onScroll = (e) => {
    const el = e.target;
    const llegueAlFondo = el.scrollTop + el.clientHeight >= el.scrollHeight - 50;
    if (llegueAlFondo) cargarMas();
  };

  const listaFiltrada = listaPokemons.filter(p =>
    p.name.toLowerCase().includes(textoBusqueda.toLowerCase().trim())
  );

  return (
    <main className="contenedor-principal">
      <header className="cabecera">
        <h1>Pokédex React</h1>
        <input
          className="buscador"
          type="text"
          placeholder="🔍 Buscar Pokémon..."
          value={textoBusqueda}
          onChange={(e) => setTextoBusqueda(e.target.value)}
        />
      </header>

      <section className="paneles-divididos">
        <div className="panel-izquierdo">
          <FotoPrincipal pokemonDetalles={detallesSeleccionado} onSeleccionar={seleccionarPokemon} />
          <DetallePanel pokemonDetalles={detallesSeleccionado} />
        </div>

        <div className="panel-derecho" onScroll={onScroll}>
          {listaFiltrada.map((poke) => (
            <TarjetaPokemon
              key={poke.name}
              nombrePokemon={poke.name}
              alHacerClic={seleccionarPokemon}
            />
          ))}
          {cargando && <p className="cargando-texto">Cargando...</p>}
        </div>
      </section>
    </main>
  );
}
