// pokepractica/pokedex-react/src/components/FotoPrincipal.jsx
import './FotoPrincipal.css';

export default function FotoPrincipal({ pokemonDetalles }) {
  if (!pokemonDetalles) {
    return (
      <div className="marco-principal vacio">
        <p>Selecciona un Pokémon de la lista lateral.</p>
      </div>
    );
  }

  return (
    <div className="marco-principal">
      <h2 className="nombre-grande">
        {pokemonDetalles.name} - N°.{pokemonDetalles.id}
      </h2>
      <img 
        src={pokemonDetalles.sprites.front_default} 
        alt={pokemonDetalles.name} 
        className="foto-gigante"
      />
    </div>
  );
}

// pokepractica/pokedex/pokedex-angular/src/app/components/foto-principal/foto-principal.component.ts
import { Component, Input, OnChanges } from '@angular/core';
import { TitleCasePipe } from '@angular/common';

@Component({
  selector: 'app-foto-principal',
  standalone: true,
  imports: [TitleCasePipe],
  templateUrl: './foto-principal.component.html',
  styleUrl: './foto-principal.component.css'
})
export class FotoPrincipalComponent implements OnChanges {
  // Recibe el SIGNAL de detalles completo del padre
  @Input() pokemonDetalles: any = null; 

  private audioActual: HTMLAudioElement | null = null;

  ngOnChanges() {
    if (this.audioActual) {
      this.audioActual.pause();
      this.audioActual.currentTime = 0;
    }
  }
  reproducirGrito() {
    const urlAudio = this.pokemonDetalles?.cries?.latest;
    if (!urlAudio) return;

    // Detenemos el anterior si existe
    if (this.audioActual) {
      this.audioActual.pause();
      this.audioActual.currentTime = 0;
    }

    this.audioActual = new Audio(urlAudio);
    this.audioActual.play();
  }
}

<div class="marco-principal">
  @if (pokemonDetalles) {
    <h2 class="nombre-grande">{{ pokemonDetalles.name | titlecase }} - N°.{{ pokemonDetalles.id }}</h2>
    
    <img [src]="pokemonDetalles.sprites.front_default" [alt]="pokemonDetalles.name"
    (click)="reproducirGrito()"
    class="imagen-clickeable">

  } @else {
    <p>Selecciona un Pokémon de la lista lateral.</p>
  }
</div>
