// pokepractica/pokedex-react/src/components/DetallePanel.jsx
import './DetallePanel.css';

export default function DetallePanel({ pokemonDetalles }) {
  if (!pokemonDetalles) return null;

  return (
    <div className="panel-datos">
      
      <div className="dato-fila">
        <span className="etiqueta">Tipo</span>
        <div className="tipos-contenedor">
          {pokemonDetalles.types.map((tipo) => (
            <span key={tipo.type.name} className="badge-tipo">
              {tipo.type.name}
            </span>
          ))}
        </div>
      </div>

      <div className="dato-fila">
        <span className="etiqueta">Altura</span>
        <span className="valor">{pokemonDetalles.height / 10} m</span>
      </div>

      <div className="dato-fila">
        <span className="etiqueta">Peso</span>
        <span className="valor">{pokemonDetalles.weight / 10} kg</span>
      </div>

    </div>
  );
}

// pokepractica/pokedex/pokedex-angular/src/app/components/detalle-panel/detalle-panel.component.ts
import { Component, Input, OnChanges, inject } from '@angular/core';
import { PokemonService } from '../../services/pokemon.service';

@Component({
  selector: 'app-detalle-panel',
  standalone: true,
  templateUrl: './detalle-panel.component.html',
  styleUrl: './detalle-panel.component.css'
})
export class DetallePanelComponent implements OnChanges {
  @Input() pokemonDetalles: any = null;

  private pokemonService = inject(PokemonService);

  historiaEspanol: string = '';

  ngOnChanges() {
    if (!this.pokemonDetalles) return;

    this.pokemonService.obtenerEspecie(this.pokemonDetalles.id).subscribe(especie => {
      const entradaEspanol = especie.flavor_text_entries.find(
        (entrada: any) => entrada.language.name === 'es'
      );
      this.historiaEspanol = entradaEspanol
        ? entradaEspanol.flavor_text.replace(/\f/g, ' ')
        : 'Historia no disponible en español.';
    });
  }

  obtenerColorBarra(valor: number): string {
    if (valor >= 80) return '#4caf50';
    if (valor >= 50) return '#ffcb05';
    return '#dc0a2d';
  }
}
@if (pokemonDetalles) {
  <div class="panel-datos">
    
    <div class="dato-fila">
      <span class="etiqueta">Tipo</span>
      <div class="tipos-contenedor">
        @for (tipo of pokemonDetalles.types; track tipo.type.name) {
          <span class="badge-tipo">{{ tipo.type.name }}</span>
        }
      </div>
    </div>

    <div class="dato-fila">
      <span class="etiqueta">Altura</span>
      <span class="valor">{{ pokemonDetalles.height / 10 }} m</span>
    </div>

    <div class="dato-fila">
      <span class="etiqueta">Peso</span>
      <span class="valor">{{ pokemonDetalles.weight / 10 }} kg</span>
    </div>

    @for (stat of pokemonDetalles.stats; track stat.stat.name) {
      <div class="dato-fila stat-fila">
        <span class="etiqueta etiqueta-stat">{{ stat.stat.name }}</span>
        <div class="barra-contenedor">
          <div 
            class="barra-relleno"
            [style.width.%]="stat.base_stat"
            [style.backgroundColor]="obtenerColorBarra(stat.base_stat)">
          </div>
          <span class="stat-numero">{{ stat.base_stat }}</span>
        </div>
      </div>
    }

    <div class="dato-fila historia-fila">
      <span class="etiqueta">Historia</span>
      <p class="historia-texto">{{ historiaEspanol }}</p>
    </div>

  </div>
}
